{% set name = "pycomlink" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pycomlink/{{ name }}/archive/{{ version }}.tar.gz
  sha256: aac59f504522942db1a79ce5e3ae2e36703222fb74a553fd534c5532460c8c80

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas >=0.22
    - matplotlib-base
    - numba
    - h5py
    - xarray
    - netcdf4
    - shapely
    - pyproj
    - tqdm
    - pykrige
    - future
    - tensorflow

test:
  imports:
    - pycomlink

about:
  home: http://github.com/pycomlink/pycomlink
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools for processing microwave link attenuation data for rainfall estimation

extra:
  recipe-maintainers:
    - cchwala
