travis:
  secure:
    BINSTAR_TOKEN: MhR94yYW/vNhv/+qFPuYmzCIcFEN5l61yTOcIime5TNSxKayfXF9uJA8ub1iq0Gu3cqGi0JArd0AslX1LoUr4dXhplj+uld3RJUThjGEvjS0q+zJWKxLarL+ylVg4V0aSZnq07TirzPItA/Epgs7KSMt64pw9U34APzF0kLHWhI6ASo9Yl8ZBmhQM/VwA6+xB4H5SdMyNSQq0RtqQImHT5wq6sp5/7ywH55rzBYCL9yegUshkKcsA23046Wql6ZZ11lzkBPmwldMz8vr5XGzAluWpYY0KmSYXH2GDDoMSrE8Dv8tnHN0Wj19k7q7gdZcmM4aCbL0Zp+WFN1wKZI5JZYUpN/kDL1r8aXyMJoexgOvlnfWrRgOlhVl5vmAida8oP2LlqYxPp1FdiUWBACh021ERZYrUwSjQCFcjiuLVQWd5H5w0Z7clxKLdIQjxvjt1kc10prwsbaoBaltx/wrlIgvH1tKh2eSF2R/2cqOfn+0MLZj/wJEY6AvhwoIlgoCmCkZwthAS0FaOXk2DnAQb1b1npSX7N2GOQ2tMLYD0e6BgggdLIihIiKxOxctJaoUdtj7cNXoyIHjEV92b0jSHb/rnFltrH1oUKlXkbc1IJd86gAI1UkqP/u11ao7VgPIBPABZ10rnenUG8BLpitC/RxdViuH4QRw/HzQ+X5a/9w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
